const cocktailData = [
  {
    strDrink: 'Mojito',
    strInstructions: 'Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish and serve with straw.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/metwgh1606770327.jpg',
    strIngredient1: 'Light rum',
    strIngredient2: 'Lime',
    strIngredient3: 'Sugar',
    strIngredient4: 'Mint',
    strIngredient5: 'Soda water',
  },
  {
    strDrink: 'Old Fashioned',
    strInstructions: 'Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg',
    strIngredient1: 'Bourbon',
    strIngredient2: 'Angostura bitters',
    strIngredient3: 'Sugar',
    strIngredient4: 'Water',
  },
  {
    strDrink: 'Long Island Tea',
    strInstructions: 'Combine all ingredients (except cola) and pour over ice in a highball glass. Add the splash of cola for color. Decorate with a slice of lemon and serve.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/nkwr4c1606770558.jpg',
    strIngredient1: 'Vodka',
    strIngredient2: 'Light rum',
    strIngredient3: 'Gin',
    strIngredient4: 'Tequila',
    strIngredient5: 'Lemon',
    strIngredient6: 'Coca-Cola',
  },
  {
    strDrink: 'Negroni',
    strInstructions: 'Stir into glass over ice, garnish and serve.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/qgdu971561574065.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'Campari',
    strIngredient3: 'Sweet Vermouth',
  },
  {
    strDrink: 'Whiskey Sour',
    strInstructions: "Shake with ice. Strain into chilled glass, garnish and serve. If served 'On the rocks', strain ingredients into old-fashioned glass filled with ice.",
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/hbkfsh1589574990.jpg',
    strIngredient1: 'Blended whiskey',
    strIngredient2: 'Lemon',
    strIngredient3: 'Powdered sugar',
    strIngredient4: 'Cherry',
    strIngredient5: 'Lemon',
  },
  {
    strDrink: 'Dry Martini',
    strInstructions: 'Straight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain in chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/6ck9yi1589574317.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'Dry Vermouth',
    strIngredient3: 'Olive',
  },
  {
    strDrink: 'Daiquiri',
    strInstructions: 'Pour all ingredients into shaker with ice cubes. Shake well. Strain in chilled cocktail glass.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/mrz9091589574515.jpg',
    strIngredient1: 'Light rum',
    strIngredient2: 'Lime',
    strIngredient3: 'Powdered sugar',
  },
  {
    strDrink: 'Margarita',
    strInstructions: 'Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg',
    strIngredient1: 'Tequila',
    strIngredient2: 'Triple sec',
    strIngredient3: 'Lime juice',
    strIngredient4: 'Salt',
  },
  {
    strDrink: 'Manhattan',
    strInstructions: 'Stirred over ice, strained into a chilled glass, garnished, and served up.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/yk70e31606771240.jpg',
    strIngredient1: 'Sweet Vermouth',
    strIngredient2: 'Bourbon',
    strIngredient3: 'Angostura bitters',
    strIngredient4: 'Ice',
    strIngredient5: 'Maraschino cherry',
    strIngredient6: 'Orange peel',
  },
  {
    strDrink: 'Moscow Mule',
    strInstructions: 'Combine vodka and ginger beer in a highball glass filled with ice. Add lime juice. Stir gently. Garnish.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/3pylqc1504370988.jpg',
    strIngredient1: 'Vodka',
    strIngredient2: 'Lime juice',
    strIngredient3: 'Ginger ale',
  },
  {
    strDrink: 'After Dinner Cocktail',
    strInstructions: 'Shake all ingredients (except lime wedge) with ice and strain into a cocktail glass. Add the wedge of lime and serve.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vtytxq1483387578.jpg',
    strIngredient1: 'Apricot brandy',
    strIngredient2: 'Triple sec',
    strIngredient3: 'Lime',
    strIngredient4: 'Lime',
  },
  {
    strDrink: 'After Supper Cocktail',
    strInstructions: 'Shake all ingredients with ice, strain into a cocktail glass, and serve.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/quyxwu1483387610.jpg',
    strIngredient1: 'Triple sec',
    strIngredient2: 'Apricot brandy',
    strIngredient3: 'Lemon juice'
  },
  {
    strDrink: 'Alabama Slammer',
    strInstructions: 'Pour all ingredients (except for lemon juice) over ice in a highball glass. Stir, add a dash of lemon juice, and serve.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/jntghf1606771886.jpg',
    strIngredient1: 'Southern Comfort',
    strIngredient2: 'Amaretto',
    strIngredient3: 'Sloe gin',
    strIngredient4: 'Lemon juice',
  },
  {
    strDrink: 'Alaska Cocktail',
    strInstructions: 'Stir all ingredients with ice, strain contents into a cocktail glass. Drop in a twist of lemon and serve.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/wsyryt1483387720.jpg',
    strIngredient1: 'Orange bitters',
    strIngredient2: 'Gin',
    strIngredient3: 'Yellow Chartreuse',
    strIngredient4: 'Lemon peel',
  },
  {
    strDrink: 'Alexander',
    strInstructions: 'Shake all ingredients with ice and strain contents into a cocktail glass. Sprinkle nutmeg on top and serve.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/0clus51606772388.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'Creme de Cacao',
    strIngredient3: 'Light cream',
    strIngredient4: 'Nutmeg',
  },
  {
    strDrink: 'Brandy Alexander',
    strInstructions: 'Shake all ingredients (except nutmeg) with ice and strain contents into a cocktail glass. Sprinkle nutmeg on top and serve.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/mlyk1i1606772340.jpg',
    strIngredient1: 'Brandy',
    strIngredient2: 'Creme de Cacao',
    strIngredient3: 'Light cream',
    strIngredient4: 'Nutmeg',
  },
  {
    strDrink: 'Alfie Cocktail',
    strInstructions: 'Combine and shake all ingredients with ice, strain into a cocktail glass, and serve.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/ypxsqy1483387829.jpg',
    strIngredient1: 'Lemon vodka',
    strIngredient2: 'Triple sec',
    strIngredient3: 'Pineapple juice',
  },
  {
    strDrink: 'Algonquin',
    strInstructions: 'Combine and shake all ingredients with ice, strain contents into a cocktail glass, and serve.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/uwryxx1483387873.jpg',
    strIngredient1: 'Blended whiskey',
    strIngredient2: 'Dry Vermouth',
    strIngredient3: 'Pineapple juice',
  },
  {
    strDrink: 'Allegheny',
    strInstructions: 'Shake all ingredients (except lemon peel) with ice and strain into a cocktail glass. Top with the twist of lemon peel and serve.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/uwvyts1483387934.jpg',
    strIngredient1: 'Dry Vermouth',
    strIngredient2: 'Bourbon',
    strIngredient3: 'Blackberry brandy',
    strIngredient4: 'Lemon juice',
    strIngredient5: 'Lemon peel',
  },
  {
    strDrink: 'Allies Cocktail',
    strInstructions: 'Stir all ingredients with ice, strain contents into a cocktail glass, and serve.',
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/qvprvp1483388104.jpg',
    strIngredient1: 'Dry Vermouth',
    strIngredient2: 'Gin',
    strIngredient3: 'Kummel',
  },
];
